name: Build test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang-version: 16.x
          - clang-version: 17.x
          - clang-version: 18.x
    runs-on: ubuntu-latest
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM 
      run: ./build-llvm.py --vendor-string Pdx --targets ARM AArch64 --projects clang lld --build-stage1-only --no-update --ref release/${{ matrix.clang-version }} -i android-kernel-toolchain-latest
    - name: Build Binutils
      run: ./build-binutils.py --targets arm-linux-gnueabi aarch64-linux-gnu -i android-kernel-toolchain-latest
