name: Build test
on:
  workflow_dispatch:
  push:

jobs:
  build-llvm-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang-version: main
          - clang-version: release/20.x
          - clang-version: release/21.x
          - clang-version: release/22.x
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: ./build-llvm.py --show-build-commands --vendor-string Pdx --targets ARM AArch64 --projects clang lld libc --no-update --ref ${{ matrix.clang-version }} -i act
    - run: ./build-rust.py --llvm-install-folder act --install-folder act --show-build-commands
#    - name: Build Binutils
#      run: ./build-binutils.py --targets arm-linux-gnueabi aarch64-linux-gnu -i android-kernel-toolchain-latest
#    - run: sudo tree android-kernel-toolchain-latest
#      continue-on-error: true
#    - name: link
#      continue-on-error: true
#      run: |
#        cd android-kernel-toolchain-latest
#        mv -v aarch64-linux-gnu aarch64-linux-android
#        mv -v arm-linux-gnueabi arm-linux-androidabei
#        cd aarch64-linux-android/bin #       for file in $(ls *); do
#            ln -sf -v  "aarch64-linux-android-${file-}" "$file"
#        done
#        cd ../../arm-linux-androidabei/bin
#        for file in $(ls *); do
#            ln -sf -v "arm-linux-androideabi-${file-}" "$file"
#        done
    - name: upload
      if: github.event_name != 'push'
      env:
       clang-version: ${{ matrix.clang-version }}
      uses: actions/upload-artifact@v7
      with:
        name: akt_${{ env.clang-version }}_${{ env.date }}
        path: act/*


  build-gcc-test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar cmake zstd ninja-build lz4 liblz4-tool liblz4-dev lzma libc6-dev-armhf --fix-broken --fix-missing

    - name: Build gcc
      run: |
        wget https://github.com/mvaisakh/gcc-build/raw/main/build-gcc.sh
        bash -x build-gcc.sh -a arm64
        
    - name: upload
      if: github.event_name != 'push'
      env:
       clang-version: ${{ matrix.arch }}
      uses: actions/upload-artifact@v7
      with:
        name: akt_${{ env.arch }}_${{ env.date }}
        path: gcc-arm64/*      
      
