name: Build test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-llvm-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang-version: 17.x
          - clang-version: 18.x
    runs-on: ubuntu-latest
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM 
      run: ./build-llvm.py --vendor-string Pdx --targets ARM AArch64 --projects clang lld --build-stage1-only --no-update --ref release/${{ matrix.clang-version }} -i android-kernel-toolchain-latest/clang
    - run: sudo tree android-kernel-toolchain-latest
#    - name: Build Binutils
#      run: ./build-binutils.py --targets arm-linux-gnueabi aarch64-linux-gnu -i android-kernel-toolchain-latest
#    - run: sudo tree android-kernel-toolchain-latest
#      continue-on-error: true
#    - name: link
#      continue-on-error: true
#      run: |
#        cd android-kernel-toolchain-latest
#        mv -v aarch64-linux-gnu aarch64-linux-android
#        mv -v arm-linux-gnueabi arm-linux-androidabei
#        cd aarch64-linux-android/bin #       for file in $(ls *); do
#            ln -sf -v  "aarch64-linux-android-${file-}" "$file"
#        done
#        cd ../../arm-linux-androidabei/bin
#        for file in $(ls *); do
#            ln -sf -v "arm-linux-androideabi-${file-}" "$file"
#        done
    - name: upload
      if: github.event_name != 'push'
      env:
       clang-version: ${{ matrix.clang-version }}
      uses: actions/upload-artifact@v4
      with:
        name: akt_${{ env.clang-version }}_${{ env.date }}
        path: android-kernel-toolchain-latest/*


  build-gcc-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm
          - arch: arm64
    runs-on: ubuntu-latest
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install flex bison ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev bc libcap-dev autoconf libgmp-dev build-essential pkg-config libmpc-dev libmpfr-dev autopoint gettext txt2man liblzma-dev libssl-dev libz-dev mercurial wget tar gcc g++ zstd --fix-broken --fix-missing
    - name: Build gcc
      run: |
        wget https://github.com/mvaisakh/gcc-build/raw/main/build-gcc.sh
        bash build-gcc.sh -a ${{ matrix.arch }}
    - name: cat 
      run: sudo tree gcc-${{ matrix.arch }}
      
    - name: upload
      if: github.event_name != 'push'
      env:
       clang-version: ${{ matrix.arch }}
      uses: actions/upload-artifact@v4
      with:
        name: akt_${{ env.arch }}_${{ env.date }}
        path: gcc-${{ env.arch }}/*      
      
