name: Build test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang-version: 14.x
          - clang-version: 15.x
          - clang-version: 16.x
          - clang-version: 17.x
    runs-on: ubuntu-latest
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM 
      run: ./build-llvm.py --vendor-string Pdx --targets ARM AArch64 --projects clang lld --build-stage1-only --no-update --ref release/${{ matrix.clang-version }} -i android-kernel-toolchain-latest/clang
    - name: Build Binutils
      run: ./build-binutils.py --targets arm-linux-gnueabi aarch64-linux-gnu -i android-kernel-toolchain-latest
    - name: link
      continue-on-error: true
      run: |
        mv -v aarch64-linux-gnu aarch64-linux-android
        mv -v arm-linux-gnueabi arm-linux-androidabei
        cd android-kernel-toolchain-latest/aarch64-linux-android
        for file in $(ls *); do
            ln -s -v "$file" "aarch64-linux-android-${file-}"
        done
        cd ../arm-linux-androidabei
        for file in $(ls *); do
            ln -s -v "$file" "arm-linux-androideabi-${file-}"
        done
    - name: upload
      if: github.event_name != 'push'
      env:
       clang-version: ${{ matrix.clang-version }}
      uses: actions/upload-artifact@v3
      with:
        name: akt_${{ env.clang-version }}_${{ env.date }}
        path: android-kernel-toolchain-latest/*
